# Mongo PersistentVolume
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-pv
  namespace: wanderlust
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/db

---
# Redis PersistentVolume
apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-pv
  namespace: wanderlust
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/redis
